config/routes.rb
Pages::Application.routes.draw do
  
  devise_for :users

  namespace :admin do 
    get "themes/index"
    resources :agencies
    resources :items
    resources :categories
    resources :fields
    resources :components, :except  => [:index, :show]
  end
  
  match ':permalink' => 'sites#show'

  root :to => 'sites#show', :permalink => 'home'
end

app/models/admin/field.rb
class Admin::Field < ActiveRecord::Base
  belongs_to :category
end

app/controllers/admin/fields_controller.rb
class Admin::FieldsController < ApplicationController

  before_filter :authenticate_user!

  # GET /admin/fields
  # GET /admin/fields.json
  def index
    @admin_fields = Admin::Field.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_fields }
    end
  end

  # GET /admin/fields/1
  # GET /admin/fields/1.json
  def show
    @admin_field = Admin::Field.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_field }
    end
  end

  # GET /admin/fields/new
  # GET /admin/fields/new.json
  def new
    @admin_field = Admin::Field.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_field }
    end
  end

  # GET /admin/fields/1/edit
  def edit
    @admin_field = Admin::Field.find(params[:id])
  end

  # POST /admin/fields
  # POST /admin/fields.json
  def create
    @admin_field = Admin::Field.new(params[:admin_field])

    respond_to do |format|
      if @admin_field.save
        format.html { redirect_to @admin_field, notice: 'Field was successfully created.' }
        format.json { render json: @admin_field, status: :created, location: @admin_field }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/fields/1
  # PUT /admin/fields/1.json
  def update
    @admin_field = Admin::Field.find(params[:id])

    respond_to do |format|
      if @admin_field.update_attributes(params[:admin_field])
        format.html { redirect_to @admin_field, notice: 'Field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/fields/1
  # DELETE /admin/fields/1.json
  def destroy
    @admin_field = Admin::Field.find(params[:id])
    @admin_field.destroy

    respond_to do |format|
      format.html { redirect_to admin_fields_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/fields_helper.rb
module Admin::FieldsHelper
end

app/views/admin/fields/_form.html.erb
<%= form_for(@admin_field) do |f| %>
  <% if @admin_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_field.errors.count, "error") %> prohibited this admin_field from being saved:</h2>

      <ul>
      <% @admin_field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/fields/edit.html.erb
<h1>Editing admin_field</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_field %> |
<%= link_to 'Back', admin_fields_path %>

app/views/admin/fields/index.html.erb
<h1>Listing admin_fields</h1>

<table>
  <tr>
    <th>Label</th>
    <th>Active</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_fields.each do |admin_field| %>
  <tr>
    <td><%= admin_field.label %></td>
    <td><%= admin_field.active %></td>
    <td><%= admin_field.category_id %></td>
    <td><%= link_to 'Show', admin_field %></td>
    <td><%= link_to 'Edit', edit_admin_field_path(admin_field) %></td>
    <td><%= link_to 'Destroy', admin_field, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Field', new_admin_field_path %>

app/views/admin/fields/new.html.erb
<h1>New admin_field</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_fields_path %>

app/views/admin/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @admin_field.label %>
</p>

<p>
  <b>Active:</b>
  <%= @admin_field.active %>
</p>

<p>
  <b>Category:</b>
  <%= @admin_field.category_id %>
</p>


<%= link_to 'Edit', edit_admin_field_path(@admin_field) %> |
<%= link_to 'Back', admin_fields_path %>