config/routes.rb
Pages::Application.routes.draw do
  
  devise_for :users

  namespace :admin do 
    get "themes/index"
    resources :agencies
    resources :items
    resources :categories
    resources :fields
    resources :components, :except  => [:index, :show]
  end
  
  match ':permalink' => 'sites#show'

  root :to => 'sites#show', :permalink => 'home'
end

app/models/admin/agency.rb
class Admin::Agency < ActiveRecord::Base
  has_many :pages
  has_many :items
  has_many :categories
  
  liquid_methods :items, :name
end

app/controllers/admin/agencies_controller.rb
class Admin::AgenciesController < ApplicationController
  
  before_filter :authenticate_user!
  
  layout 'admin'
  
  # GET /admin/agencies
  # GET /admin/agencies.json
  def index
    @admin_agencies = Admin::Agency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_agencies }
    end
  end

  # GET /admin/agencies/1
  # GET /admin/agencies/1.json
  def show
    @admin_agency = Admin::Agency.where(:id => params[:id]).includes(:pages)[0]
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_agency }
    end
  end

  # GET /admin/agencies/new
  # GET /admin/agencies/new.json
  def new
    @admin_agency = Admin::Agency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_agency }
    end
  end

  # GET /admin/agencies/1/edit
  def edit
    @admin_agency = Admin::Agency.find(params[:id])
  end

  # POST /admin/agencies
  # POST /admin/agencies.json
  def create
    @admin_agency = Admin::Agency.new(params[:admin_agency])

    respond_to do |format|
      if @admin_agency.save
        format.html { redirect_to @admin_agency, notice: 'Agency was successfully created.' }
        format.json { render json: @admin_agency, status: :created, location: @admin_agency }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/agencies/1
  # PUT /admin/agencies/1.json
  def update
    @admin_agency = Admin::Agency.find(params[:id])

    respond_to do |format|
      if @admin_agency.update_attributes(params[:admin_agency])
        format.html { redirect_to @admin_agency, notice: 'Agency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/agencies/1
  # DELETE /admin/agencies/1.json
  def destroy
    @admin_agency = Admin::Agency.find(params[:id])
    @admin_agency.destroy

    respond_to do |format|
      format.html { redirect_to admin_agencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/agencies_helper.rb
module Admin::AgenciesHelper
end

app/views/admin/agencies/_form.html.erb
<%= form_for(@admin_agency) do |f| %>
  <% if @admin_agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_agency.errors.count, "error") %> prohibited this admin_agency from being saved:</h2>

      <ul>
      <% @admin_agency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/agencies/edit.html.erb
<h1>Editing admin_agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_agency %> |
<%= link_to 'Back', admin_agencies_path %>

app/views/admin/agencies/index.html.erb
<h1>Listing admin_agencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Domain</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_agencies.each do |admin_agency| %>
  <tr>
    <td><%= admin_agency.name %></td>
    <td><%= admin_agency.domain %></td>
    <td><%= link_to 'Show', admin_agency %></td>
    <td><%= link_to 'Edit', edit_admin_agency_path(admin_agency) %></td>
    <td><%= link_to 'Destroy', admin_agency, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Agency', new_admin_agency_path %>

app/views/admin/agencies/new.html.erb
<h1>New admin_agency</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_agencies_path %>

app/views/admin/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_agency.name %>
</p>

<p>
  <b>Domain:</b>
  <%= @admin_agency.domain %>
</p>

<h2>Pages</h2>
<% @admin_agency.pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= truncate(page.content, :length => 100) %></td>
    <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>

<br>

<%= link_to 'Edit', edit_admin_agency_path(@admin_agency) %> |
<%= link_to 'Back', admin_agencies_path %>