config/routes.rb
Pages::Application.routes.draw do
  
  devise_for :users

  namespace :admin do 
    get "themes/index"
    resources :agencies
    resources :items
    resources :categories
    resources :fields
    resources :components, :except  => [:index, :show]
  end
  
  match ':permalink' => 'sites#show'

  root :to => 'sites#show', :permalink => 'home'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/agency.rb
class Admin::Agency < ActiveRecord::Base
  has_many :pages
  has_many :items
  has_many :categories
  
  liquid_methods :items, :name
end

app/models/admin/category.rb
class Admin::Category < ActiveRecord::Base
  belongs_to :agency
  has_many :fields
end

app/models/admin/component.rb
class Admin::Component < ActiveRecord::Base
  attr_accessible :agency_id, :component_type_id, :content, :template_id, :title, :permalink
  
  belongs_to :component_type
  belongs_to :template, :class_name => 'Component'
  
  scope :by_permalink, lambda { |permalink, agency_id| where(:permalink => permalink, :agency_id => agency_id) }
  scope :by_agency, lambda { |agency_id| where(:agency_id => agency_id) }
  scope :page, where(:component_type_id => 2)
  scope :template, where(:component_type_id => 1)
  scope :stylesheet, where(:component_type_id => 3)
  scope :javascript, where(:component_type_id => 4)
  
  
  liquid_methods :title, :content, :permalink
end

app/models/admin/component_type.rb
class Admin::ComponentType < ActiveRecord::Base
  attr_accessible :label
  
  has_many :components
end

app/models/admin/field.rb
class Admin::Field < ActiveRecord::Base
  belongs_to :category
end

app/models/admin/item.rb
class Admin::Item < ActiveRecord::Base
  belongs_to :agency

  scope :by_agency, lambda { |agency_id| where(:agency_id => agency_id) }
  
  liquid_methods :title, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  before_filter :authenticate_user!

  layout 'admin'
  
  # GET /admin/items
  # GET /admin/items.json
  def index
    @admin_items = Admin::Item.by_agency(@current_agency.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_items }
    end
  end

  # GET /admin/items/1
  # GET /admin/items/1.json
  def show
    @admin_item = Admin::Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_item }
    end
  end

  # GET /admin/items/new
  # GET /admin/items/new.json
  def new
    @admin_item = Admin::Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_item }
    end
  end

  # GET /admin/items/1/edit
  def edit
    @admin_item = Admin::Item.find(params[:id])
    @categories = @current_agency.categories
  end

  # POST /admin/items
  # POST /admin/items.json
  def create
    @admin_item = Admin::Item.new(params[:admin_item])

    respond_to do |format|
      if @admin_item.save
        format.html { redirect_to @admin_item, notice: 'Item was successfully created.' }
        format.json { render json: @admin_item, status: :created, location: @admin_item }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/items/1
  # PUT /admin/items/1.json
  def update
    @admin_item = Admin::Item.find(params[:id])

    respond_to do |format|
      if @admin_item.update_attributes(params[:admin_item])
        format.html { redirect_to @admin_item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/items/1
  # DELETE /admin/items/1.json
  def destroy
    @admin_item = Admin::Item.find(params[:id])
    @admin_item.destroy

    respond_to do |format|
      format.html { redirect_to admin_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :current_agency

  private

  def current_agency
    @current_agency = Admin::Agency.find_by_domain(request.host)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_filter :current_agency
   
  def current_agency
    @current_agency = Admin::Agency.find_by_domain(request.host)
  end
   
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    if params[:permalink]
      @page = Page.by_permalink(params[:permalink], @current_agency.id)[0]
      raise ActiveRecord::RecordNotFound, 'Page not found' if @page.nil?
    else
      @page = Page.find(params[:id])
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  
  layout 'website'

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Admin::Component.page.by_permalink(params[:permalink], @current_agency.id)[0]
    raise ActiveRecord::RecordNotFound, 'Page not found' if @page.nil?
    
    @agency = @current_agency
    
    respond_to do |format|
      format.html { render :layout => false}
      format.json { render json: @page }
    end
  end
end

app/helpers/admin/agencies_helper.rb
module Admin::AgenciesHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/components_helper.rb
module Admin::ComponentsHelper
end

app/helpers/admin/fields_helper.rb
module Admin::FieldsHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/templates_helper.rb
module Admin::TemplatesHelper
end

app/helpers/admin/themes_helper.rb
module Admin::ThemesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def liquidize(content, arguments)
    Liquid::Template.parse(content).render(arguments)
  end
end

app/views/admin/pages/index.html.erb
<% content_for :sidebar do %>
  <%= render 'sidebar' %>
<% end %>
<%= link_to 'New Page', new_admin_page_path, :class => 'btn' %>
<%= link_to 'New Template', new_admin_template_path, :class => 'btn' %>

app/views/admin/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="#" class="brand">Real Admin</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><%= link_to 'Themes', admin_themes_index_path %></li>
          <li><%= link_to 'Items', admin_items_path %></li>
          <li><%= link_to 'Agency Details', edit_admin_agency_path(@current_agency) %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to 'Public Website', root_path, :target => '_blank' %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Dashboard Super Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    "admin", :media => "all" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="http://twitter.github.com/bootstrap/examples/images/favicon.ico">
    <link rel="apple-touch-icon" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-114x114.png">
  </head>

  <body>
    <%= render 'admin/shared/navbar' %>
    
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= yield :breadcrumbs %>
        </div>       
      </div>
      <div class="row-fluid"> 
        <div class="span3">
          <%= yield :sidebar %>
        </div>
        <div class="span9">          
          <%= yield %>
        </div>
      </div>
    </div>
   <%= javascript_include_tag "admin" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pages</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= image_tag 'bg1.jpg', :class => 'bg' %>
  <div id="page-content">
    <div id="center">
      <div data-pjax-container id="signin-box">
        <% unless flash[:alert].nil? %>
          <div class="msg">
            <span class="alert"><%= alert %></span>
            <span class="notice"><%= notice %></span>
          </div>
        <% end %>
        <% unless flash[:error].nil? %>
          <div class="msg">
            <span class="error"><%= error %></span>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/website.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pages</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Project name</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="span11">
          <%= yield %>
        </div>
        <div class="span1">&nbsp;</div>
        <div class="span4">
          <h3>Sidebar</h3>
          <ul>
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :template %><br />
    <%= f.number_field :template %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Template:</b>
  <%= @page.template %>
</p>

<p>
  <b>Content:</b>
  <%= simple_format @page.content %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>